Update module import path for changed @actions/http-client@2.x package structure
The module path usable with the 1.x series of the package caused build to fail:

src/installer.ts:8:23 - error TS2307: Cannot find module '@actions/http-client/auth' or its corresponding type declarations.